### ISSUE TITLE
[Bug] Home screen is presented when first installing the application

### ISSUE THREAD

**Issue by minhnimble** [nguyenvhung9420/survey-app-hungnguy#2]
# Issue

The user is being sent to the Home screen when first installing the application on the phone. As a result, the survey list API call is failed and the app is showing a black screen at this point.

Here is the error log that I received after building the application:
```
"COme to RefreshAccessTokenUseCase"
"requestConfiguration: refreshCurrentAccessToken(token: \"\")"
2022-04-21 15:01:38.457473+0700 survey_hung[67074:2941372] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics
Error in refreshAccessTokenUseCase: keyNotFound(CodingKeys(stringValue: "data", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"data\", intValue: nil) (\"data\").", underlyingError: nil))
2022-04-21 15:01:39.434223+0700 survey_hung[67074:2941372] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics
"Error when surveysQuery = fetch(query: query) = Received a 401 error. Data returned as a String was: {\"errors\":[{\"message\":\"The access token is invalid\",\"extensions\":{\"code\":\"invalid_token\",\"state\":\"unauthorized\"}}]}"
```

# Expected

Login screen should be shown first for authentication.

# Step To Reproduce 

Just simply build the app freshly from Production scheme:

https://user-images.githubusercontent.com/70877098/164398022-bc1f0cfb-3444-4a05-9ebd-6889efd6f058.MP4

**Comment by nguyenvhung9420** [comment]
Ok, thanks for your comment, this bug seems severe, let me recheck my flow and get back with a fix.

**Comment by minhnimble** [comment]
LGTM now 🚀
